language: objective-c
osx_image: xcode8.3
before_install:
    - pod install --repo-update
script:
  - xcodebuild clean build test -workspace GitLabKit.xcworkspace -scheme GitLabKit CODE_SIGNING_REQUIRED=NO
